### ISSUE TITLE
in need of newbie instructions for running the example

### ISSUE THREAD

**Issue by oconnor663** [sken77/BLAKE3jni#2]
I'd like to build and run the example locally, but it's been a long time since I've used Java, and it's not clear to me what I should do. I see the `build.sbt` file, so I figured `sbt compile` might be a good starting point, but that command fails with this error:

```
[error] /tmp/BLAKE3jni/src/main/java/org/scash/NativeBLAKE3.java:142:1: incompatible types: java.nio.Buffer cannot be converted to java.nio.ByteBuffer
[error]         nativeByteBuffer.set(byteBuff.clear());
```

Is that expected? Would it be possible to give the full series of commands to run the example, so that I could just paste things into my terminal? :)

**Comment by sken77** [comment]
What java version are you using? As for sbt. i'm planning on building on maven since sbt is really a scala build system.

**Comment by oconnor663** [comment]
Sorry, I totally should've included that with my original question. I'm on an up-to-date Arch Linux machine, with OpenJDK version 8.u242. I think that's "the default" on Arch, but I don't use Java very frequently.

The commands I ran were:

```
git clone https://github.com/sken77/BLAKE3jni
cd BLAKE3jni
sbt compile
```

**Comment by oconnor663** [comment]
And now that I try it again, it looks like 1bf44d303322c2747a23adb1fc6796f3bb604d98 fixed the problem as advertised :)

**Comment by sken77** [comment]
Im glad it works out. Im planning on releasing the artifacts directly to maven. So now all you would need to do is add it as a dependency. If you any other issues please let me know. Im working on adding the stream soon
